name: CI Builds

on: [push]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '25'
      - name: Maven build
        run: ./mvnw --batch-mode --no-transfer-progress clean verify --file pom.xml
      - name: Native build
        run: ./mvnw --batch-mode --no-transfer-progress -Pnative -DskipTests clean native:compile --file pom.xml
